name: Run Robot Framework Tests on Android Emulator

on:
 workflow_dispatch:
 push:
    branches: [master]
 pull_request:
    branches: [master]

jobs:
 build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download APK from GitHub Release
      run: |
        wget https://github.com/ophinst/hyppe-automation-test/releases/download/stg/app-release.apk

    - name: Set up Android Emulator and Install APK
      uses: reactivecircus/android-emulator-runner@v2
      with:
         api-level: 28
         target: default
         arch: x86
         profile: pixel
         script: |
           sleep 30 # Wait for the emulator to be fully ready
           adb install ./app-release.apk
         cores: 2
         avd-name: test
         force-avd-creation: true
         emulator-boot-timeout: 600
         emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
         disable-animations: true
         disable-spellchecker: false
         disable-linux-hw-accel: auto
         enable-hw-keyboard: false
         channel: stable

    - name: Run Robot Framework Tests
      uses: tarathep/robotframework-github-action@v1.0
      with:
        tests_dir: '${{ github.workspace }}/tests'
        reports_dir: '${{ github.workspace }}/tests/robot/reports'

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ${{ github.workspace }}/tests/robot/reports/*.xml

 generate_report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: test-results

    - name: Generate and Upload HTML Report
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: '${{ github.workspace }}/tests/robot/reports'
        summary: 'true'
        only_summary: 'false'
        show_passed_tests: 'true'

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: ${{ github.workspace }}/tests/robot/reports/*.html
