name: Run Robot Framework Tests on Android Emulator

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
 build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download APK from GitHub Release
      run: |
        wget https://github.com/ophinst/hyppe-automation-test/releases/download/stg/app-release.apk

    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: default
        arch: x86
        profile: pixel

    - name: Install APK on Emulator
      run: |
        adb install ./your-apk-name.apk

    - name: Run Robot Framework Tests
      uses: tarathep/robotframework-github-action@v1.0
      with:
        tests_dir: '${{ github.workspace }}/tests'
        reports_dir: '${{ github.workspace }}/tests/robot/reports'
