name: Run Robot Framework Tests on Android Emulator

on:
 workflow_dispatch:
 push:
    branches: [master]
 pull_request:
    branches: [master]

jobs:
 build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download APK from GitHub Release
      run: |
        wget https://github.com/ophinst/hyppe-automation-test/releases/download/stg/app-release.apk

    - name: Install Appium and Robot Framework AppiumLibrary
      run: |
        npm install -g appium@1.22.0
        pip install --upgrade robotframework-appiumlibrary

    # - name: Start Appium Server
    #   run: appium

    # - name: Wait for emulator to be ready
    #   run: |
    #    until adb devices | grep emulator-5554; do
    #     echo "Waiting for emulator to be ready..."
    #     sleep 5
    #    done

    - name: Adjust permissions for Robot Framework reports
      run: chmod -R 777 ${{ github.workspace }}

    - name: Install requirements
      run: pip install -r ${{ github.workspace }}/requirements.txt

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
         node-version: '14'

    - name: Set up Android Emulator and Install APK
      uses: reactivecircus/android-emulator-runner@v2
      with:
         api-level: 28
         target: default
         arch: x86_64
         profile: pixel
         script: |
           sleep 30 # Wait for the emulator to be fully ready
           adb install ./app-release.apk
           adb devices
           
         cores: 2
         avd-name: emulator-5554
         force-avd-creation: true
         emulator-boot-timeout: 600
         emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
         disable-animations: true
         disable-spellchecker: false
         disable-linux-hw-accel: auto
         enable-hw-keyboard: false
         channel: stable

    - name: Run Tests
      run: |
         adb devices
         robot --variable APP_PACKAGE:com.hyppe.hyppeapp --variable UDID:emulator-5554 tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ${{ github.workspace }}/*.xml

 generate_report:
    if: always()
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: test-results

    - name: Generate and Upload HTML Report
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: '${{ github.workspace }}'
        summary: 'true'
        only_summary: 'false'
        show_passed_tests: 'true'

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: ${{ github.workspace }}/*.html
